version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=spring_boot_db